// All user-facing copy lives here so localisation is straightforward later.
export const strings = {
  app: {
    name: "MaizAI",
    tagline: "Maize disease detection for Cameroonian farmers",
  },
  auth: {
    signIn: "Sign in",
    signOut: "Sign out",
    email: "E-mail address",
    password: "Password",
    signInButton: "Sign in to MaizAI",
    signingIn: "Signing in…",
    invalidCredentials: "Invalid e-mail address or password.",
    networkError: "Could not reach the server. Check your connection.",
    requestAccess: "Request access",
    requestAccessTitle: "Request access",
    requestAccessSubtitle: "Fill in the form below and an administrator will review your request.",
    fullName: "Full name",
    affiliation: "Affiliation (optional)",
    reason: "Reason for access",
    submitRequest: "Submit request",
    submitting: "Submitting…",
    requestSent: "Request submitted",
    requestSentDetail: "You will be notified when your request has been reviewed.",
    changePasswordTitle: "Set your password",
    changePasswordSubtitle: "Choose a secure password to activate your account.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    passwordsDoNotMatch: "Passwords do not match.",
    setPassword: "Set password and continue",
  },
  capture: {
    title: "Capture",
    instruction: "Point the camera at a maize leaf and tap to capture",
    analysing: "Analysing leaf…",
    cameraPermissionTitle: "Camera access required",
    cameraPermissionBody:
      "MaizAI needs camera access to capture maize leaf images for disease classification.",
    openSettings: "Open settings",
    pendingCount: (n: number) => `${n} pending`,
  },
  result: {
    title: "Result",
    diseaseLabel: "Detected condition",
    confidenceLabel: "Confidence",
    probabilitiesLabel: "Class probabilities",
    recommendationLabel: "Recommendation",
    urgencyLabel: "Urgency",
    capturedAt: "Captured",
    inferenceTime: (ms: number) => `${ms} ms on-device`,
    syncStatus: "Sync status",
    synced: "Synced to cloud",
    pendingSync: "Pending synchronisation",
    saveAndCaptureAnother: "Save and capture another",
    share: "Share result",
    delete: "Delete",
    healthyAdvice: "This leaf appears healthy. Continue routine monitoring.",
  },
  history: {
    title: "History",
    empty: "No captures yet",
    emptyDetail: "Your captured leaves will appear here.",
    filterAll: "All",
    filterHealthy: "Healthy",
    filterDiseased: "Diseased",
    filterPending: "Pending sync",
    pullToRefresh: "Pull to sync",
    deleteConfirmTitle: "Delete capture",
    deleteConfirmBody: "This will permanently remove the capture and its classification from this device.",
    cancel: "Cancel",
    delete: "Delete",
  },
  settings: {
    title: "Settings",
    profile: "Profile",
    changePassword: "Change password",
    sync: "Synchronisation",
    lastSync: "Last synchronised",
    never: "Never",
    pendingCaptures: (n: number) => `${n} pending`,
    syncNow: "Sync now",
    syncing: "Syncing…",
    cache: "Local data",
    clearHistory: "Clear local history",
    clearHistoryConfirm:
      "This removes all captures, classifications, and recommendations from this device. Cloud data is not affected.",
    refreshThresholds: "Refresh rule thresholds",
    about: "About",
    version: "Version",
    openSource: "Open source on GitHub",
    reportBug: "Report a bug",
    license: "MIT Licence",
    account: "Account",
    signOut: "Sign out",
    signOutConfirm: "Are you sure you want to sign out?",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    offline: "You are offline. This action requires a connection.",
    modelLoadFailed: "The AI model could not be loaded. Please reinstall the app.",
    syncFailed: "Synchronisation failed. Your captures are saved locally.",
  },
  diseases: {
    Healthy: "Healthy",
    Common_Rust: "Common Rust",
    Gray_Leaf_Spot: "Gray Leaf Spot",
    Blight: "Blight",
  } as Record<string, string>,
  urgency: {
    LOW: "Low",
    MEDIUM: "Medium",
    HIGH: "High",
  } as Record<string, string>,
} as const;
